### PR TITLE
Replace Xiaomi DRM changes and introduce new features

### PR DESCRIPTION
**Pull request by ivecera**
The patch series reworks all needed DRM stuff from scratch. To use all new functionality a corresponding changes for android_device_sdm710-common (https://github.com/SDM710-Development/android_device_xiaomi_sdm710-common/pull/47) need to be used as well.

**Patch 1** - Reverts all changes introduced by Xiaomi
**Patch 2** - Fixes a compiler warning related to incorrect type in formatting string
**Patch 3** - Extends backlight driver notifier by new event BACKLIGHT_UPDATED that is sent when backlight values has been changed
**Patch 4-9** - Misc bugfixes backported from CAF
**Patch 10** - Removes unnecessary delay during waiting for ctl_start on command mode panels
**Patch 11** - Add support for getting panel physical type from DTS
**Patch 12** - Fixes dips present during AOD exit on OLED panels
**Patch 13** - Set physical panel type to OLED for sdm710 based Xiaomi devices
**Patch 14** - Moves msm_drm_register() to async probe to speed-up boot time
**Patch 15** - Performance improvement that avoids copying of fence names to userspace
**Patch 16** - Adds support for inverted display brightness value
**Patch 17** - Updates DTS to use `qcom,mdss-dsi-bl-inverted-dbv` introduced by patch 16 instead of Xiaomi's original `qcom,mdss-dsi-bl-dcs-type-ss`
**Patch 18-21** - Extend existing MSM DRM notifiers by adding new blank modes so they corresponds to SDE power modes 1:1 and by adding new transitions from & to these new blank modes
**Patch 22-27** - Convert existing users of Xiaomi's drm notifiers (removed by patch 1) to use existing MSM DRM notifiers
**Patch 28** - Adds plane property for FOD
**Patch 29** - Adds an ability to modify/update existing plane property
**Patch 30** - Removes ZPOS plane property value limit
**Patch 31** - Defines a special value for ZPOS property that identifies FOD layer
**Patch 32** - Uses functionality from patch 29 to translate special value for ZPOS (patch 31) and to set FOD property when the special value is present in ZPOS property
**Patch 33** - Increases number of SDE stages
**Patch 34** - Increases HS Tx timeout (taken from Xiaomi sources)
**Patch 35-39** - Add new sysfs attribute group in dsi_display for new knobs to be accessible at `/sys/devices/platform/soc/soc:qcom,dsi-display-primary`
**Patch 40-45** - Add support for Doze mode
**Patch 46-47** - Add support for HBM mode (controlled by `hbm` sysfs knob)
**Patch 48** - Adds support for multi-purpose global dimming layer (full-screen layer for global attentuation)
**Patch 49** - Adds new global dimming layer type for FOD handling
**Patch 50-62** - Implement FOD handling using FOD dimming layer type
**Patch 63-73** - Implement DC dimming (aka AntiFlicker feature) using TOP dimming layer type

All important changes are exhaustively commented in descriptions of relevant patches.

### CODE REVIEW

**Review by uixdess — APPROVED** [review]
Works flawlessly on sirius. Well done!

**Comment by NaassomDourado** [comment]
Awesome, go ahead!!

**Comment by uixdess** [comment]
> Awesome, go ahead!!

I am waiting for feedback from grus.

**Review by NaassomDourado — APPROVED** [review]

**Review by DobreDomitian — APPROVED** [review]

**Comment by uixdess** [comment]
Works on grus as it should

**Comment by RDS-007** [comment]
> Works on grus as it should

yes , working

**Pull request merged**
